[package]
name = "arugula-testkit"
description = "The test harness for arugulad's integration tests"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
arugula-proto = { workspace = true, features = ["fixtures"] }
serde_json = { workspace = true }
tokio-tungstenite = { workspace = true }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true, features = ["signal", "process"] }

[lints]
workspace = true
